// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6_xYG2D_86p1ZBa86LugxpMEca3qjEk',
    appId: '1:311781754479:web:1ef96400dd30376e866f9a',
    messagingSenderId: '311781754479',
    projectId: 'foodiee-4662d',
    authDomain: 'foodiee-4662d.firebaseapp.com',
    storageBucket: 'foodiee-4662d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzscMXMyZ1BCsARB2HepVfQUVxrqoWvPw',
    appId: '1:311781754479:android:9a84c5526d05bfd2866f9a',
    messagingSenderId: '311781754479',
    projectId: 'foodiee-4662d',
    storageBucket: 'foodiee-4662d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Ec7RUGujswSK0RNXgVGax3nAgKSjij0',
    appId: '1:311781754479:ios:626a932dffd950a9866f9a',
    messagingSenderId: '311781754479',
    projectId: 'foodiee-4662d',
    storageBucket: 'foodiee-4662d.appspot.com',
    iosBundleId: 'com.example.foodiee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Ec7RUGujswSK0RNXgVGax3nAgKSjij0',
    appId: '1:311781754479:ios:2f8671339a94d3ab866f9a',
    messagingSenderId: '311781754479',
    projectId: 'foodiee-4662d',
    storageBucket: 'foodiee-4662d.appspot.com',
    iosBundleId: 'com.example.foodiee.RunnerTests',
  );
}
